[features]
seeds = false
[programs.localnet]
wmp_staking = "DdWrg36YWCZeBna3X5PDvRpSc7UxV84qH2kaCVtXevv2"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/poznyakbogdan/.config/solana/wmp-staking-devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
